"""added auth join

Revision ID: 1d9b3bf8aa84
Revises: 2f86362ae83a
Create Date: 2018-12-13 19:40:57.345401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9b3bf8aa84'
down_revision = '2f86362ae83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'portfolios', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('portfolios', 'account_id')
    # ### end Alembic commands ###
