"""updated relations

Revision ID: 22bbaf462e5c
Revises: 029363210bd0
Create Date: 2018-12-13 18:38:07.127057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bbaf462e5c'
down_revision = '029363210bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companies', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'portfolio_id')
    # ### end Alembic commands ###
